In [1]:
#Numpy dtype hierarchy
import numpy as np

In [2]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)

In [3]:
np.issubdtype(ints.dtype, np.integer)

True

In [4]:
np.issubdtype(floats.dtype, np.floating)

True

In [5]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [6]:
np.int64.mro()

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [7]:
# Advanced array manipulation
#Reshaping arrays

In [8]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [10]:
# multidimensional array also can reshape

In [11]:
arr.reshape((4,2)).reshape((2,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
arr2 = np.arange(15)
arr2.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [13]:
other_array = np.ones((3,5))
other_array.shape

(3, 5)

In [14]:
arr2.reshape(other_array.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
# flattening and raveling is opposite of reshaping
arr3 = np.arange(15).reshape((5,3))
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
arr3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# ravel does not produce the copy of underlying data
# while flatten produce copy
arr3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
# Concatenating and splitting arrays
x = np.array([[1,2,3],
              [4, 5,6]])
y = np.array([[7, 8, 9],
              [10, 11, 12]])
z = np.concatenate([x, y], axis=0)
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:
w = np.concatenate([x, y], axis=1)
w

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
# equivalent axis=0 operation is
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
# equivalent axis=1 operation is 
np.hstack((x, y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [22]:
# split slices an array into a multiple arrays
a = np.random.randn(5,2)
a

array([[-0.10453904, -1.17531229],
       [ 1.06870954,  0.58946033],
       [ 0.94023479,  0.17244006],
       [ 0.12611606, -0.15293597],
       [ 1.60158262,  0.03220096]])

In [23]:
first, second, third = np.split(a, [1,2])

In [24]:
first

array([[-0.10453904, -1.17531229]])

In [25]:
second

array([[1.06870954, 0.58946033]])

In [26]:
third

array([[ 0.94023479,  0.17244006],
       [ 0.12611606, -0.15293597],
       [ 1.60158262,  0.03220096]])

In [28]:
# Fancy indexing
arr = np.arange(10) * 100
arr

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [29]:
indices = [7, 1, 2, 6]
arr[indices]

array([700, 100, 200, 600])

In [30]:
arr2 = np.arange(5)
inds = [4,3]
arr2[inds]

array([4, 3])

In [31]:
# Alternative way 
arr.take(indices)

array([700, 100, 200, 600])

In [32]:
arr.put(indices, 42)   # replace value 42 in array of indices

In [33]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [34]:
# to use along other axes
inds1 = [2, 0, 2, 1]
arr3  = np.random.randn(2, 4)
arr3

array([[ 0.19059155, -1.74084535, -0.68474064,  0.03278423],
       [-0.8796315 , -1.38135105,  1.06068283,  0.47131704]])

In [35]:
arr3.take(inds1, axis=1)

array([[-0.68474064,  0.19059155, -0.68474064, -1.74084535],
       [ 1.06068283, -0.8796315 ,  1.06068283, -1.38135105]])