In [3]:
# Broadcasting
# It describes how arithmetic works between arrays of different shapes

In [2]:
import numpy as np

In [5]:
arr = np.arange(5)
arr * 4

array([ 0,  4,  8, 12, 16])

In [6]:
# another example
arr2 = np.random.randn(4, 3)
arr2.mean()

-0.01972743412271986

In [8]:
demeaned = arr2 - arr2.mean(0)
demeaned

array([[-1.31442014, -0.22827162, -0.08327394],
       [ 1.40314076, -0.29060126, -0.58023154],
       [-0.19415347, -1.75719011,  1.88402066],
       [ 0.10543285,  2.276063  , -1.22051518]])

In [9]:
demeaned.mean(0)

array([-6.93889390e-18,  0.00000000e+00, -5.55111512e-17])

In [15]:
row_means = arr2.mean(1)
row_means

array([-0.561716  ,  0.15770855, -0.04216841,  0.36726612])

In [16]:
row_means.reshape((4, 1))

array([[-0.561716  ],
       [ 0.15770855],
       [-0.04216841],
       [ 0.36726612]])

In [18]:
demeaned = arr2 - row_means.reshape((4, 1))
demeaned

array([[-0.86617197,  0.90463154, -0.03845957],
       [ 1.13196437,  0.12287735, -1.25484172],
       [-0.2654529 , -1.14383454,  1.40928743],
       [-0.37530111,  2.47998404, -2.10468293]])

In [3]:
# broadcasting over other axes
# np.newaxis == 1
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr_3d = arr[:, np.newaxis, :]
arr_3d

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [5]:
arr_3d.shape

(4, 1, 4)

In [6]:
arr_1d = np.random.normal(size=3)
arr_1d

array([-0.56586927, -1.62110399,  1.73260651])

In [8]:
arr_1d[:, np.newaxis]

array([[-0.56586927],
       [-1.62110399],
       [ 1.73260651]])

In [9]:
arr_1d[np.newaxis, :]

array([[-0.56586927, -1.62110399,  1.73260651]])

In [10]:
# 3d broadcasting 
arr2 = np.random.randn(3, 4, 5)
arr2

array([[[ 1.62918911,  0.88621769,  0.01550989,  0.02554573,
          1.0954663 ],
        [ 2.14796265,  1.64220436, -0.20319524, -0.58997249,
         -1.33236736],
        [-0.41502664, -1.2185831 , -0.83080401, -2.29973871,
         -0.03890263],
        [-2.73338588, -0.9591773 ,  0.1363283 , -0.40778276,
          0.70461351]],

       [[ 1.20993295,  0.28676098, -0.13311367, -1.41535271,
          1.21053423],
        [-2.37543888, -0.02804924,  0.21297287,  0.25879516,
          0.51410643],
        [-1.03347623, -0.90752269,  0.48656293, -1.34092184,
          0.9737224 ],
        [ 0.82849624,  0.06090049, -1.03691837,  0.56653723,
          1.26805639]],

       [[ 1.1092662 ,  0.23195228, -1.15619097, -0.27633642,
          0.58171653],
        [ 0.5533882 , -1.37311077,  1.81422004, -0.00355167,
         -0.16769407],
        [ 1.06440626,  0.71863824,  1.33631184, -0.28441741,
         -0.13049053],
        [-0.14621322, -0.1687335 ,  0.30238069,  1.58099384,
          0

In [12]:
depth_means = arr2.mean(2)   # 3d depth mean
depth_means

array([[ 0.73038574,  0.33292638, -0.96061102, -0.65188083],
       [ 0.23175235, -0.28352273, -0.36432708,  0.3374144 ],
       [ 0.09808152,  0.16465035,  0.54088968,  0.47936702]])

In [13]:
depth_means.shape

(3, 4)

In [14]:
demeaned = arr2 - depth_means[:, :, np.newaxis]
demeaned

array([[[ 0.89880336,  0.15583195, -0.71487586, -0.70484001,
          0.36508055],
        [ 1.81503627,  1.30927798, -0.53612163, -0.92289887,
         -1.66529374],
        [ 0.54558438, -0.25797208,  0.12980701, -1.33912769,
          0.92170839],
        [-2.08150505, -0.30729647,  0.78820913,  0.24409806,
          1.35649433]],

       [[ 0.97818059,  0.05500863, -0.36486603, -1.64710507,
          0.97878188],
        [-2.09191615,  0.25547349,  0.4964956 ,  0.54231789,
          0.79762916],
        [-0.66914915, -0.5431956 ,  0.85089002, -0.97659475,
          1.33804949],
        [ 0.49108184, -0.27651391, -1.37433277,  0.22912284,
          0.93064199]],

       [[ 1.01118467,  0.13387076, -1.2542725 , -0.37441795,
          0.48363501],
        [ 0.38873786, -1.53776112,  1.64956969, -0.16820202,
         -0.33234441],
        [ 0.52351658,  0.17774856,  0.79542215, -0.82530709,
         -0.67138021],
        [-0.62558024, -0.64810052, -0.17698633,  1.10162682,
          0

In [15]:
# setting array values by broadcasting
arr3 = np.zeros((4, 3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr3[:]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr3[:] = 5
arr3

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
col = np.array([1.28, -0.42, 0.44, 1.6])
arr3[:] = col[:, np.newaxis]
arr3

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [19]:
arr3[:2] = [[-1.37], [0.509]]
arr3

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [20]:
arr4 = np.zeros((4,4))
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
row = np.arange(4)
row

array([0, 1, 2, 3])

In [22]:
arr4[:] = row[:4]
arr4

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])