In [23]:
# Advance ufunc usage
# ufunc instance methods
import numpy as np


In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.add.reduce(arr)   # sum of all elements in that matrix

45

In [6]:
np.add.reduce(np.arange(3))

3

In [7]:
arr.sum()

45

In [9]:
np.random.seed(12346)
arr2 = np.random.randn(5, 5)
arr2

array([[-8.99822478e-02,  7.59372617e-01,  7.48336101e-01,
        -9.81497953e-01,  3.65775545e-01],
       [-3.15442628e-01, -8.66135605e-01,  2.78568155e-02,
        -4.55597723e-01, -1.60189223e+00],
       [ 2.48256116e-01, -3.21536673e-01, -8.48730755e-01,
         4.60468309e-04, -5.46459347e-01],
       [ 2.53915229e-01,  1.93684246e+00, -7.99504902e-01,
        -5.69159281e-01,  4.89244731e-02],
       [-6.49092950e-01, -4.79535727e-01, -9.53521432e-01,
         1.42253882e+00,  1.75403128e-01]])

In [12]:
arr2[:, :-1] < arr2[:, 1:]

array([[ True, False, False,  True],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [14]:
arr3 =  np.arange(15).reshape(3, 5)

In [15]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
# cumulative sum in row
np.add.accumulate(arr3, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [17]:
# subtract
x, y = np.random.randn(3, 4), np.random.randn(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [18]:
result

array([[[-0.07129513,  1.80587986,  0.04445711, -0.77002945,
          0.37076839],
        [-0.48729668,  1.38987831, -0.37154444, -1.18603099,
         -0.04523316],
        [-0.49099936,  1.38617563, -0.37524711, -1.18973367,
         -0.04893584],
        [-0.70194533,  1.17522966, -0.58619309, -1.40067964,
         -0.25988181]],

       [[-0.5388528 ,  1.33832219, -0.42310056, -1.23758711,
         -0.09678928],
        [-0.39734742,  1.47982757, -0.28159518, -1.09608173,
          0.0447161 ],
        [-0.78758534,  1.08958965, -0.6718331 , -1.48631965,
         -0.34552182],
        [-2.05029021, -0.17311522, -1.93453796, -2.74902452,
         -1.60822669]],

       [[ 0.2637349 ,  2.14090989,  0.37948715, -0.43499941,
          0.70579842],
        [-1.3352883 ,  0.54188669, -1.21953606, -2.03402261,
         -0.89322478],
        [-1.37407525,  0.50309974, -1.25832301, -2.07280956,
         -0.93201173],
        [-0.70013722,  1.17703777, -0.58438498, -1.39887153,
         -0

In [19]:
# reduceat
arr5 = np.arange(10)
np.add.reduceat(arr5, [0, 5, 8])


array([10, 18, 17])

In [20]:
# Structured and Record arrays
# array with multiple data types
dtype = [('x', np.float64), ('y', np.int32)]
structured_arr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
structured_arr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [21]:
structured_arr[0]

(1.5, 6)

In [23]:
structured_arr['x']

array([1.5       , 3.14159265])

In [24]:
dtype = [('a', np.int64), ('b', np.float64)]  # (a, b) = ( int64, float64)
dtype

[('a', numpy.int64), ('b', numpy.float64)]

In [25]:
sarr = np.array([(1, 3), (4, -4)], dtype=dtype)
sarr

array([(1,  3.), (4, -4.)], dtype=[('a', '<i8'), ('b', '<f8')])

In [26]:
sarr['a']  # int

array([1, 4])

In [27]:
sarr['b'] # float

array([ 3., -4.])

In [2]:
# nested dtypes
dtype = [('x', np.int64, 3), ('y', np.int32)]
dtype

[('x', numpy.int64, 3), ('y', numpy.int32)]

In [3]:
arr = np.zeros(4, dtype=dtype)

In [4]:
arr  # x field is array of length 3

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [5]:
arr['x']

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
arr[0]['x']

array([0, 0, 0])

In [7]:
# nested dtypes
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1,2), 5), ((3,4), 6)], dtype=dtype)
data

array([((1., 2.), 5), ((3., 4.), 6)],
      dtype=[('x', [('a', '<f8'), ('b', '<f4')]), ('y', '<i4')])

In [10]:
# More about sorting
arr = np.random.randn(6)
arr.sort()

In [11]:
arr

array([-2.76617919, -1.5396627 , -0.06347791,  0.24102844,  0.38622377,
        1.32743595])

In [12]:
arr2 = np.random.randn(3, 5)
arr2.sort()

In [13]:
arr2

array([[-1.63974582, -0.59763053,  0.28942434,  0.46937971,  0.71411833],
       [-0.54281054, -0.39616554, -0.13657154,  0.9218099 ,  2.11160185],
       [-1.98513543, -1.48162322, -0.44015049, -0.36933982,  0.73679796]])

In [14]:
arr2[:, 0].sort() # sort first column


In [15]:
arr2

array([[-1.98513543, -0.59763053,  0.28942434,  0.46937971,  0.71411833],
       [-1.63974582, -0.39616554, -0.13657154,  0.9218099 ,  2.11160185],
       [-0.54281054, -1.48162322, -0.44015049, -0.36933982,  0.73679796]])

In [16]:
# np.sort(arr) Created new sorted copy of an array
arr2 = np.random.randn(5)
arr2

array([ 0.26230017, -0.51132614, -0.12572001,  0.08522267, -1.41865038])

In [17]:
np.sort(arr2)


array([-1.41865038, -0.51132614, -0.12572001,  0.08522267,  0.26230017])

In [18]:
arr2

array([ 0.26230017, -0.51132614, -0.12572001,  0.08522267, -1.41865038])

In [19]:
arr3 = np.random.randn(3, 5)
arr3

array([[-0.73042454,  1.17947904,  0.67109797,  0.19771892, -0.28951588],
       [ 0.72268309, -0.63066253,  1.40416585,  0.87210809,  1.42825231],
       [ 0.91107523, -0.15520405, -0.15730607, -1.1285002 ,  0.95967911]])

In [20]:
arr3.sort(axis=1) # sort in row

In [21]:
arr3

array([[-0.73042454, -0.28951588,  0.19771892,  0.67109797,  1.17947904],
       [-0.63066253,  0.72268309,  0.87210809,  1.40416585,  1.42825231],
       [-1.1285002 , -0.15730607, -0.15520405,  0.91107523,  0.95967911]])

In [22]:
# Indirect sorts: argsort and  lexsort

In [24]:
# argsort=> gives sorted index of an array

values = np.array([5, 0, 1, 3, 2])
indexer = values.argsort()
indexer


array([1, 2, 4, 3, 0])

In [25]:
values[indexer]

array([0, 1, 2, 3, 5])

In [26]:
arr5 = np.random.randn(3, 5)
arr5

array([[ 0.21150275, -0.05905748, -0.14826563, -0.3834446 ,  0.0782083 ],
       [ 0.46745257, -0.26481944,  1.24118612, -0.17145755,  0.16964802],
       [-1.54669353,  1.48773952, -1.28225221,  0.71079988,  1.01624343]])

In [28]:
arr5[0] = values
arr5

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 0.46745257, -0.26481944,  1.24118612, -0.17145755,  0.16964802],
       [-1.54669353,  1.48773952, -1.28225221,  0.71079988,  1.01624343]])

In [29]:
arr5[:, arr5[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.26481944,  1.24118612,  0.16964802, -0.17145755,  0.46745257],
       [ 1.48773952, -1.28225221,  1.01624343,  0.71079988, -1.54669353]])

In [30]:
# lexsort=>
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones','Arnold', 'Arnold', 'Jones', 'Walters'])


In [31]:
sorter = np.lexsort((first_name, last_name))
sorter

array([1, 2, 3, 0, 4])

In [32]:
# Alternative Sort Algorithms
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])
values

array(['2:first', '2:second', '1:first', '1:second', '1:third'],
      dtype='<U8')

In [33]:
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer

array([2, 3, 4, 0, 1])

In [35]:
values = np.random.randn(5,5)
values

array([[-0.71486642, -1.29199803, -0.3582325 , -0.98888984,  0.02123126],
       [ 0.33236303,  0.15177183,  1.90033731,  0.83124531,  0.74523712],
       [ 1.35132902, -1.38792235,  1.00244586, -0.7468444 ,  0.04378623],
       [ 0.07764228,  0.60052787,  1.08699231, -0.15055231,  0.64260943],
       [ 2.49024025, -0.6164884 ,  1.98869395, -2.6295802 ,  0.27792825]])

In [38]:
indexer = values.argsort(kind='heapsort')
indexer

array([[1, 3, 0, 2, 4],
       [1, 0, 4, 3, 2],
       [1, 3, 4, 2, 0],
       [3, 0, 1, 4, 2],
       [3, 1, 4, 2, 0]])

In [41]:
# partially sorting arrays
arr = np.random.randn(20)
arr

array([ 0.03441568,  0.52391476, -1.0461316 , -0.09094272, -1.4173442 ,
        1.28215894,  0.3207373 ,  0.24897166, -0.58740924,  1.2995327 ,
        0.43237529, -1.55300181,  0.61950881,  2.4418195 , -1.16032727,
       -0.34266443, -0.92156587,  1.11812168, -0.68281124, -0.87978384])

In [42]:
arr.shape

(20,)

In [43]:
np.partition(arr, 3)

array([-1.55300181, -1.4173442 , -1.16032727, -1.0461316 , -0.87978384,
       -0.09094272, -0.92156587, -0.34266443, -0.58740924, -0.68281124,
        0.03441568,  0.43237529,  0.61950881,  2.4418195 ,  0.52391476,
        0.24897166,  0.3207373 ,  1.11812168,  1.28215894,  1.2995327 ])

In [44]:
indices = np.argpartition(arr, 3)
indices

array([11,  4, 14,  2, 19,  3, 16, 15,  8, 18,  0, 10, 12, 13,  1,  7,  6,
       17,  5,  9])

In [45]:
arr.take(indices)

array([-1.55300181, -1.4173442 , -1.16032727, -1.0461316 , -0.87978384,
       -0.09094272, -0.92156587, -0.34266443, -0.58740924, -0.68281124,
        0.03441568,  0.43237529,  0.61950881,  2.4418195 ,  0.52391476,
        0.24897166,  0.3207373 ,  1.11812168,  1.28215894,  1.2995327 ])

In [46]:
# Finding elements in sorted array
# perform binary search on sorted array

In [48]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(7)

2

In [49]:
arr.searchsorted([0, 12, 15])

array([0, 3, 4])