In [56]:
# A n-dimensional array:(ndarray)

In [2]:
import numpy as np


In [3]:
# Generate some random data
data = np.random.randn(2,3)

In [4]:
data

array([[-1.1466759 ,  1.67196669,  1.68983247],
       [-0.88500312,  0.93446469, -1.00713413]])

In [5]:
# Mathematical operation
data * 5

array([[-5.73337948,  8.35983346,  8.44916237],
       [-4.4250156 ,  4.67232345, -5.03567063]])

In [6]:
data + data

array([[-2.29335179,  3.34393338,  3.37966495],
       [-1.77000624,  1.86892938, -2.01426825]])

In [7]:
data.shape

(2, 3)

In [8]:
data.dtype

dtype('float64')

In [9]:
# Creating Ndarrays
list1 = [1,3.4,-3,3]
list1


[1, 3.4, -3, 3]

In [10]:
arr1 = np.array(list1)
arr1

array([ 1. ,  3.4, -3. ,  3. ])

In [11]:
arr1.ndim



1

In [12]:
arr1.dtype

dtype('float64')

In [13]:
list2 = [[1,2,3],[4,5,6]]
arr2 = np.array(list2)

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.dtype

dtype('int64')

In [16]:
# creatng zeros array
zero = np.zeros(5)
zero

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.empty((4,4))

array([[4.67213066e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
# Identity matrix
np.eye(3,3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# dataTypes of ndarrays
arr1 = np.array([1,23,4], dtype=np.float64)
arr2= np.array([3,4,5], dtype=np.int64)

arr1.dtype
arr2.dtype

dtype('int64')

In [22]:
# Arithmetic Operations
arr = np.array([[1,2,3], [4, 5, 6]], dtype=np.float64)
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [23]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [26]:
arr / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [27]:
arr2 = np.array([[1,4,5], [5,6,4]], dtype=np.float64)
arr > arr2

array([[False, False, False],
       [False, False,  True]])

In [29]:
# indexing and Slicing
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr[6]

6

In [31]:
arr[5:8]

array([5, 6, 7])

In [32]:
arr[1:3] = 0

In [33]:
arr

array([0, 0, 0, 3, 4, 5, 6, 7, 8, 9])

In [34]:
# np array are mutable
arr_slice = arr[5:8]
arr_slice


array([5, 6, 7])

In [35]:
arr_slice[1] = 65
arr

array([ 0,  0,  0,  3,  4,  5, 65,  7,  8,  9])

In [47]:
# copy of slice of an array
arr_slice = arr[1:3].copy()
arr_slice[0] = 5
arr_slice

array([5, 0])

In [48]:
arr

array([ 0,  5,  0,  3,  4,  5, 65,  7,  8,  9])

In [49]:
arr2d = np.array([[1,3,4], [4,5,6], [8,3,2]])
arr2d.ndim

2

In [50]:
arr2d[1]

array([4, 5, 6])

In [51]:
arr2d[1][0]

4

In [52]:
# 3d array
arr3d = np.array([[[1, 2, 3,], [3,4,5]],[[5,3,5],[3,3,4]]])

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 3, 5],
        [3, 3, 4]]])

In [53]:
arr3d.ndim

3

In [54]:
arr3d[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [56]:
arr3d[1, 0]

array([5, 3, 5])

In [58]:
#indexing with slices
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [59]:
arr[3:5]

array([3, 4])

In [79]:
#boolean indexing
names = np.array(['bob', 'michael', 'binish', 'saman', 'rojan', 'pramod'])
data = np.random.randn(1,6)
names

array(['bob', 'michael', 'binish', 'saman', 'rojan', 'pramod'],
      dtype='<U7')

In [87]:
data 

array([[0.        , 1.25931168, 0.26852768, 0.26872668, 0.        ,
        0.        ]])

In [81]:
names == 'michael'

array([False,  True, False, False, False, False])

In [85]:
data[data > 0] 

array([1.25931168, 0.26852768, 0.26872668])

In [86]:
data[data < 0] = 0
data

array([[0.        , 1.25931168, 0.26852768, 0.26872668, 0.        ,
        0.        ]])

In [89]:
# fancy indexing
arr3 = np.empty((8, 4))
arr3

array([[4.67213078e-310, 0.00000000e+000, 6.91870537e-310,
        6.91870429e-310],
       [6.91870539e-310, 4.67212897e-310, 6.91870429e-310,
        6.91870538e-310],
       [6.91870429e-310, 6.91870537e-310, 6.91870536e-310,
        6.91870539e-310],
       [6.91870502e-310, 6.91870532e-310, 6.91870534e-310,
        6.91870429e-310],
       [6.91870527e-310, 6.91870529e-310, 6.91870429e-310,
        6.91870529e-310],
       [6.91870537e-310, 6.91870538e-310, 6.91870438e-310,
        6.91870429e-310],
       [6.91870438e-310, 6.91870533e-310, 6.91870429e-310,
        6.91870538e-310],
       [6.91870529e-310, 6.91870429e-310, 6.91870537e-310,
        6.91870438e-310]])

In [95]:
for i in range(8):
    arr3[i] = i
    
arr3

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [96]:
arr3[[2,5,7]]

array([[2., 2., 2., 2.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])